import os

from flask import Blueprint, render_template
import gh_md_to_html

from blueprints.utils.files import discover_files_in_directory, discover_folders_in_directory

app_bp = Blueprint('app', __name__, url_prefix='/app')

@app_bp.route("/courses")
def courses():
  folder_information = discover_folders_in_directory('local_data/Learning')


  return render_template('app/courses.html', folder_information=folder_information)

@app_bp.route("/home")
def home():
  files = discover_files_in_directory('local_data/Learning', '.md')
  sorted_files = sorted(zip(files['names'], files['paths']), key=lambda x: x[0])

  files['names'] = [name for name, path in sorted_files]
  files['paths'] = [path for name, path in sorted_files]
  
  return render_template('app/home.html', files=files)



@app_bp.route("/file/<path:filepath>")
def file(filepath):
  if not os.path.exists(filepath):
    return render_template('error.html', error_code=404, error_message="Die angeforderte Datei wurde nicht gefunden."), 404
  html = gh_md_to_html.main(filepath, core_converter="OFFLINE", )

  file_name = os.path.basename(filepath)

  # delete temporary file generated by gh_md_to_html  
  if os.path.exists(file_name.replace(".md", ".html")):
    os.remove(file_name.replace(".md", ".html"))
  
  # Parse the HTML to extract the content within the first <div> tag and remove the head
  parsedHTML = "<"+ html.replace(html.split('div')[0], "")

  return render_template('app/markdown.html', markdown=(parsedHTML), file_name=file_name)

@app_bp.route("/folder/<path:folderpath>")
def folder(folderpath):
  if not os.path.exists(folderpath):
    return render_template('error.html', error_code=404, error_message="Der angeforderte Ordner wurde nicht gefunden."), 404

  folder_name = os.path.basename(folderpath)
  files = discover_files_in_directory(folderpath, '.md')
  sorted_files = sorted(zip(files['names'], files['paths']), key=lambda x: x[0])

  files['names'] = [name for name, path in sorted_files]
  files['paths'] = [path for name, path in sorted_files]

  folders = discover_folders_in_directory(folderpath)
  sorted_folders = sorted(zip(folders['names'], folders['paths']), key=lambda x: x[0])

  folders['names'] = [name for name, path in sorted_folders]
  folders['paths'] = [path for name, path in sorted_folders]

  return render_template('app/folder.html', folder_name=folder_name, files=files, folders=folders)

@app_bp.route('/profile') 
def profile():
  return render_template('app/profile.html', name="test")