from flask import Blueprint, render_template, url_for
import gh_md_to_html
import os

dev_bp = Blueprint('dev', __name__, url_prefix='/dev')

@dev_bp.route("/md")
def md():
    file_name = 'sample_md.md'

    html = gh_md_to_html.main('data/' + file_name, core_converter="OFFLINE", )

    # delete temporary file generated by gh_md_to_html  
    if os.path.exists(file_name.replace(".md", ".html")):
        os.remove(file_name.replace(".md", ".html"))



    # Parse the HTML to extract the content within the first <div> tag and remove the head
    parsedHTML = "<"+ html.replace(html.split('div')[0], "")
    print(parsedHTML)

    return render_template('app/markdown.html', markdown=(parsedHTML) )